### ISSUE TITLE
swift gesture error - always includes background

### ISSUE THREAD

**Issue by nahyunkwon** [KwonNH/ZoomableUI#5]
I get currently available views using CGRect.intersects in hasIntersection() method. 
This solution has a problem that I always get a background view as a current view no matter the background is apparent or not.

**Comment by KwonNH** [comment]
Solution
1) disable access to the background view with a swift gesture
2) change hasIntersection() method not to use CGRect.intersects

**Comment by nahyunkwon** [comment]
1. initial state: highlight the first object from the whole object list (ex. house1, not background!)
    * single tap on 'background': read highlighted the first object
    * single tap on other objects: read tapped object
    * swipe: start from the first object
2. zoomed: highlight the first object from the current objects (do not include background.)
